### PR TITLE
Pull request for deleteQuestion - "/question/delete/{questionId}

### PR DESCRIPTION
**Pull request by shilpa1193**
Pull request for deleteQuestion - "/question/delete/{questionId}

### CODE REVIEW

**Review by somya0610 — CHANGES_REQUESTED** [review]
Kindly do the below changes before I merge the code:
1. QuestionController: Modify comment section for createQuestion() and prettify the code
2. QuestionDao: Make the method deleteQuestion() to return void. Do the related changes in its related files
3. QuestionEntity: No commit required for this class.

**Comment by shilpa1193** [comment]
Changes done as per changes raised.

**Comment by somya0610** [comment]
Merged changes done for feature deleteQuestion - "/question/delete/{questionId}"

**Review by somya0610 — APPROVED** [review]
Approved changes for deleteQuestion - "/question/delete/{questionId}"

**Pull request merged**
